### ISSUE TITLE
Nginx: Can't change header after puts/write

### ISSUE THREAD

**Issue by m1cr0man** [felipedaragon/remy#4]
The following error is produced by Nginx if you try to modify the header after any calls to puts/write.
`*1 attempt to set ngx.header.HEADER after sending out response headers`
This is expected behaviour, as per the [Nginx Lua Documentation](https://github.com/openresty/lua-nginx-module#ngxheaderheader).

> Setting ngx.header.HEADER after sending out response headers (either explicitly with ngx.send_headers or implicitly with ngx.print and similar) will throw out a Lua exception.

As per [their recommendation](https://github.com/openresty/lua-nginx-module#ngxprint), requests to puts/write should be buffered or saved and all the chunks should be printed once at the end, allowing changes to the header at any time. This is also more performant, as the response is not being flushed every call.

At the moment, this issue is resulting in the loss of session cookies in Sailor, making it mostly incompatible with Nginx.

**Comment by m1cr0man** [comment]
I have already made a fix.

**Comment by felipedaragon** [comment]
Thank you!
